
def sum(x: int, y: int): int {
     return x + y;
}

def sum(a: int, b: int): int {      
    return a + b;
}

def main(): int {
    var x, y, z, i, result: int;
    var a, b: bool;

    x = 2;
    y = 6;

    //b = y;

    while (z > 10) {
        var x: int;
        z = z - x;

        for (i = 0; i < 10; i = i + 1) {
            z = sum(sum(x, y), 100 * i);
        }
    }

    result = sum(a, b);     

    return 0;
}
