def sum(x: int, y: int): int {
    return x + y;
}

def main(): int {
    var a = 5, b = 10, c, d: int;
    var x = true, y = true, w: bool;

    a = a + b;
    b = b - a;
    c = 2 * a;
    c = b / 2;
    a += 1;
    b -= 1;
    c *= 2;
    a /= 3;

    x = x || y;
    y = y && y;
    x = a < b;
    x = a <= a;
    y = c > a;
    y = b >= c;
    w = !x;
    d = -10;

    //Operações que geram erro
    x = a; 
    a = x;  
    f = a + b;  
    x = sum(a, b);  
    a = sub(b, c); 
    a = a + x;     
    a = x + y;
    a = x - y;
    a = x * y;
    a = x / y;
    x = x < y;
    x = a && b;
    return 0;
}